### ISSUE TITLE
About page bug

### ISSUE THREAD

**Issue by ErinUntermeyer** [leighlars/WeatherOrNot#43]
- [ ] Test
- [x] Fix Bug
When you navigate to the About page, this error appears in the console:

`Warning: validateDOMNesting(...): Text nodes cannot appear as a child of <thead>.
    in thead (at About.tsx:76)
    in table (at About.tsx:75)
    in div (at About.tsx:69)
    in section (at About.tsx:23)
    in About (at App.tsx:44)
    in Route (at App.tsx:41)
    in main (at App.tsx:34)
    in div (at App.tsx:30)
    in App (at src/index.tsx:8)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.tsx:8)`

**Comment by leighlars** [comment]
I'll look into this!
